### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by cquanu** [MichaelBelgium/freshping-discord#1]
Hi @MichaelBelgium, Any idea why? Appreciate the help in advance :)

**Comment by MichaelBelgium** [comment]
Euh, what exactly isn't working? I'm not using this webhook anymore since a 4-5 weeks or so.

**Comment by cquanu** [comment]
I followed the README exactly but couldn't get any notification from discord.
Maybe Freshping changed their request.

![app freshping io_org_41079_settings_integrations](https://user-images.githubusercontent.com/16508884/74250666-e9364c80-4d25-11ea-9b2c-690008107076.png)

``` json
{
    "request_start_time": "2020-02-11T15:25:47.910225+00:00",
    "check_target_response_time": 100,
    "check_id": 1,
    "recently_started_check_start_time": null,
    "recently_started_check_http_status_code": null,
    "http_status_code": 200,
    "check_state_name": "Available",
    "check_name": "Example check",
    "recently_started_check_state_name": null,
    "application_name": "Webhook test",
    "recently_started_check_response_time": null,
    "request_url": "https://www.example.com/",
    "check_computed_target_response_time": 200,
    "response_time": 50
}
```

**Comment by MichaelBelgium** [comment]
Is that the full json that gets send to the webhook? If so, yeah looks like they changed it.

**Comment by cquanu** [comment]
Yes that’s the full JSON request sent to the webhook.

**Comment by cquanu** [comment]
I managed to get it worked with a custom PHP file. Closing this.

**Comment by MichaelBelgium** [comment]
You could do a PR where u update the getters in the classes
