### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by Erdack54** [MichaelBelgium/freshping-discord#2]
Hello, I install the webhook correctly but I do not know what "DISCORD_TOKEN" and how to incorporate it into webhook.php :/ Can you help me pls ?

**Comment by MichaelBelgium** [comment]
You need to [create a discord bot](https://discord.com/developers/applications) thats allowed to send the messages from the webhook in ur discord server. After creating u get a token which then u use as define

**Comment by MichaelBelgium** [comment]
Also according to #1 the response from freshping has changed so I'm afraid the classes `FreshpingResponse` and `FreshpingResponseData` might not work anymore. I didn't have the chance to update these as I can't test it ..

**Comment by Erdack54** [comment]
Oh I see, thank you for your answer :) I'll test and see if it works otherwise too bad ¯\_(ツ)_/¯

**Comment by MichaelBelgium** [comment]
I quickly tested it and It should still work:

```
michael (85499), AL (16501), 2020-05-22 16:05:09
Example check (1): Available, 200 ms, 2020-05-22 16:05:09
```
